Repository saltastroops/salt-api, pull requests merged in 2023-03, with the labels that each got.

#201 Remove unused method.
  saltapi/repository/proposal_repository.py
Labels: duplicate

#195 Update investigator's proposal approval status endpoint
  saltapi/service/permission_service.py
  saltapi/service/proposal_service.py
  saltapi/web/api/proposals.py
  saltapi/web/schema/proposal.py
  tests/integration/proposals/test_update_investigator_proposal_approval_status.py
Labels: enhancement

#204 Add proposal approval repository function
  saltapi/repository/proposal_repository.py
  saltapi/web/schema/user.py
  tests/integration/proposals/test_update_investigator_proposal_approval_status.py
Labels: bug
